name: testy
favicon: null
layout_spectrum: 0.88237
typography_spectrum: 0.75123
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#267ebb'
    - '#75040f'
    - '#95bad9'
    - '#a96a70'
  brandStrength: 0.5
  lightness: 0.6875
  saturation: 0.3125
  rhythmicContrast: 0
purpose: []
