name: testy
favicon: null
layout_spectrum: 0.88237
typography_spectrum: 0.75123
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fffffd'
    - '#060000'
    - '#661b2f'
    - '#cc6848'
    - '#84b8e4'
  brandStrength: 0.5
  lightness: 0.6875
  saturation: 0.3125
  rhythmicContrast: 0
purpose: []
